#!/usr/bin/env python3
"""Shared LoopX process contract constants."""

STAGE_SEQUENCE = [
    "environment_check",
    "requirement_intake",
    "requirement_interview",
    "spec_draft",
    "spec_review",
    "mode_selection",
    "solution_design",
    "solution_review",
    "test_design",
    "test_review",
    "development",
    "quality_audit",
    "code_review",
    "test_execution",
    "health_gate",
    "release_readiness",
    "final_report",
]
STAGES = set(STAGE_SEQUENCE)
STAGE_STATUSES = {"PASS", "CHANGES_REQUIRED", "BLOCKED", "SKIPPED", "ACCEPTED_RISK", "NEED_HUMAN"}
PASSING_STATUSES = {"PASS", "ACCEPTED_RISK"}
FULL_REQUIRED_PASS_STAGES = [
    "solution_design",
    "solution_review",
    "test_design",
    "test_review",
    "development",
    "quality_audit",
    "code_review",
    "test_execution",
    "health_gate",
    "release_readiness",
]
STAGE_RESULT_FILES = {
    "environment_check": "00-environment-check.json",
    "requirement_intake": "01-requirement-intake.json",
    "requirement_interview": "02-requirement-interview.json",
    "spec_draft": "03-spec-draft.json",
    "spec_review": "04-spec-review.json",
    "mode_selection": "05-mode-selection.json",
    "solution_design": "06-solution-design.json",
    "solution_review": "07-solution-review.json",
    "test_design": "08-test-design.json",
    "test_review": "09-test-review.json",
    "development": "10-development.json",
    "quality_audit": "11-quality-audit.json",
    "code_review": "12-code-review.json",
    "test_execution": "13-test-execution.json",
    "health_gate": "14-health-gate.json",
    "release_readiness": "15-release-readiness.json",
    "final_report": "16-final-report.json",
}
DEFAULT_STAGE_OWNERS = {
    "environment_check": "environment-check-agent",
    "requirement_intake": "project-manager",
    "requirement_interview": "requirement-manager",
    "spec_draft": "requirement-manager",
    "spec_review": "requirement-manager",
    "mode_selection": "controller",
    "solution_design": "solution-designer",
    "solution_review": "solution-reviewer",
    "test_design": "test-designer",
    "test_review": "test-reviewer",
    "development": "development",
    "quality_audit": "quality-auditor",
    "code_review": "code-reviewer",
    "test_execution": "test-runner",
    "health_gate": "quality-auditor",
    "release_readiness": "release-manager",
    "final_report": "release-manager",
}
STAGE_DISPLAY_NAMES = {
    "environment_check": "环境检查",
    "requirement_intake": "需求接收",
    "requirement_interview": "需求采访",
    "spec_draft": "规格草稿",
    "spec_review": "规格审核",
    "mode_selection": "执行等级选择",
    "solution_design": "方案设计",
    "solution_review": "方案审核",
    "test_design": "测试设计",
    "test_review": "测试审核",
    "development": "开发",
    "quality_audit": "质量审计",
    "code_review": "代码审查",
    "test_execution": "测试执行",
    "health_gate": "健康门",
    "release_readiness": "发布就绪",
    "final_report": "最终报告",
}
CONFIRMATION_GATE_STAGES = {
    "requirement_interview": "spec_draft",
    "solution_review": "test_design",
    "test_review": "development",
    "release_readiness": "final_report",
}
